name: seecar
description: "SeeCar - Car discovery app for college project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ðŸ”¹ State Management
  provider: ^6.1.2

  # ðŸ”¹ Firebase (FREE TIER)
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  firebase_storage: ^11.6.0
  shared_preferences: ^2.2.3
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1


  # ðŸ”¹ Biometric auth
  local_auth: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
